eureka:
  client:
    serviceUrl:
#    注册中心
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
#  应用名称,利用 Feign 的声明式 HTTP 客户端，通过注解的形式很容易
#做到不同服务之间的相互调用。
    name: feign
#开启熔断器,我们的服务最终是部署在服务器上，因为各种原因，服务难免
#会发生故障，那么其他服务去调用这个服务就会调不到，甚至会一直卡在那里，
#导致用户体验不好。针对这个问题，我们就需要对服务接口做错误处理，一旦
#发现无法访问服务，则立即返回并报错，我们捕捉到这个异常就可以以可读化
#的字符串返回到前端。
feign:
  hystrix:
     enabled: true

